### ISSUE TITLE
langchain.verbose

### ISSUE THREAD

**Issue by SambitSahuIT** [krishnaik06/Updated-Langchain#1]
I am facing this issue repeatedly - 

Traceback (most recent call last):
  File "d:\Project\Langchain\TUTORIAL1\chatbot\locallama.py", line 26, in <module>
    llm=Ollama(model="gemma:2b")
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sambi\anaconda3\Lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1066, in pydantic.main.validate_model
  File "pydantic\fields.py", line 439, in pydantic.fields.ModelField.get_default
  File "c:\Users\sambi\anaconda3\Lib\site-packages\langchain_core\language_models\base.py", line 71, in _get_verbosity
    return get_verbose()
           ^^^^^^^^^^^^^
  File "c:\Users\sambi\anaconda3\Lib\site-packages\langchain_core\globals.py", line 50, in get_verbose
    import langchain  # type: ignore[import]
    ^^^^^^^^^^^^^^^^
  File "d:\Project\Langchain\TUTORIAL1\chatbot\langchain.py", line 36, in <module>
    llm = ChatOpenAI(model="gpt-3.5-turbo")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\sambi\anaconda3\Lib\site-packages\langchain_core\load\serializable.py", line 120, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1066, in pydantic.main.validate_model
  File "pydantic\fields.py", line 439, in pydantic.fields.ModelField.get_default
  File "c:\Users\sambi\anaconda3\Lib\site-packages\langchain_core\language_models\base.py", line 71, in _get_verbosity
    return get_verbose()
           ^^^^^^^^^^^^^
  File "c:\Users\sambi\anaconda3\Lib\site-packages\langchain_core\globals.py", line 72, in get_verbose
    old_verbose = langchain.verbose
                  ^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'langchain' has no attribute 'verbose' (most likely due to a circular import)
PS D:\Project\Langchain\TUTORIAL1>

**Comment by Tanaykmr** [comment]
Where are you facing this issue?
